spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:  openapi, swagger-ui

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory
    username: inventory
    password: inventory
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:  openapi, swagger-ui